
const REQUEST_LOGIN = 'REQUEST_LOGIN';
const RECEIVE_TOKEN = 'RECEIVE_TOKEN';
const DELETE_TOKEN = 'DELETE_TOKEN';
const GET_STORES = 'GET_SOTRES';
const RECEIVE_SOTRES = 'RECEIVE_SOTRES'
const GET_ADDRESSES = 'GET_ADDRESSES'
const POST_ADDRESSES = 'POST_ADDRESSES'
const PUT_ADDRESSES = 'PUT_ADDRESSES'
const DELETE_ADDRESSES = 'DELETE_ADDRESSES'
const RECEIVE_ADDRESSES = 'RECEIVE_ADDRESSES'
const POST_ADDRESS = 'POST_ADDRESS'
const SAVE_STORES = 'SAVE_STORES'
const GET_STOREDETAIL = 'GET_STOREDETAIL'
const RECEIVE_STOREDETAIL = 'RECEIVE_STOREDETAIL'
const SAVE_STOREDETAIL = 'SAVE_STOREDETAIL'
const CLEAR_STOREDETAIL = 'CLEAR_STOREDETAIL'
const SAVE_ORDER = 'SAVE_ORDER'
const GET_ORDER = 'GET_ORDER'
const RECEIVE_ORDER = 'RECEIVE_ORDER'

export {
  REQUEST_LOGIN,
  RECEIVE_TOKEN,
  DELETE_TOKEN,
  GET_STORES,
  RECEIVE_SOTRES,
  GET_ADDRESSES,
  POST_ADDRESSES,
  PUT_ADDRESSES,
  DELETE_ADDRESSES,
  RECEIVE_ADDRESSES,
  POST_ADDRESS,
  SAVE_STORES,
  GET_STOREDETAIL,
  RECEIVE_STOREDETAIL,
  SAVE_STOREDETAIL,
  CLEAR_STOREDETAIL,
  SAVE_ORDER,
  GET_ORDER,
  RECEIVE_ORDER
}