
const REQUEST_LOGIN = 'REQUEST_LOGIN';
const RECEIVE_TOKEN = 'RECEIVE_TOKEN';
const DELETE_TOKEN = 'DELETE_TOKEN';
const GET_STORES = 'GET_SOTRES';
const RECEIVE_SOTRES = 'RECEIVE_SOTRES'

export {
  REQUEST_LOGIN,
  RECEIVE_TOKEN,
  DELETE_TOKEN,
  GET_STORES,
  RECEIVE_SOTRES
}